# Generated by Django 5.2 on 2025-04-28 15:04

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('contents', wagtail.fields.StreamField([('demo_block', 1)], blank=True, block_lookup={0: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 1: ('wagtail.blocks.StructBlock', [[('image', 0)]], {})})),
            ],
            options={
                'verbose_name': 'デモページ',
                'verbose_name_plural': 'デモページ',
                'ordering': ['-first_published_at'],
            },
            bases=('wagtailcore.page',),
        ),
    ]
