# Generated by Django 5.2 on 2025-05-01 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', models.CharField()),
            ],
            options={
                'verbose_name': 'Demo Page',
                'verbose_name_plural': 'Demo Pages',
            },
            bases=('wagtailcore.page',),
        ),
    ]
